import { storage } from "../storage.js";
import { actOnRecommendation } from "../actions.js";
import type { StrategicObjective, BusinessGoal } from "../../shared/schema.js";

interface OverdueGoalAction {
  goalId: string;
  goalTitle: string;
  assignedAgent: string;
  actionType: string;
  priority: 'low' | 'medium' | 'high';
  recommendations: string[];
  deadline: Date;
}

export class StrategyExecutor {
  /**
   * Automatically execute actions for overdue strategic goals
   */
  async executeOverdueGoalActions(): Promise<OverdueGoalAction[]> {
    const goals = await this.getOverdueGoals();
    const actions: OverdueGoalAction[] = [];
    
    for (const goal of goals) {
      const action = await this.createActionForGoal(goal);
      if (action) {
        actions.push(action);
        // Submit the action through the governance system
        await this.submitGoalAction(action);
      }
    }
    
    return actions;
  }
  
  /**
   * Identify overdue strategic goals that need immediate action
   */
  async getOverdueGoals(): Promise<StrategicObjective[]> {
    const objectives = await storage.getStrategicObjectives();
    const now = new Date();
    
    // Consider a goal overdue if:
    // 1. Progress < 70% and deadline passed, OR
    // 2. Progress < 50% and deadline is within 7 days, OR  
    // 3. Progress < 30% and deadline is within 14 days
    const overdueGoals = objectives.filter(obj => {
      const daysToDealline = this.getDaysToDeadline(obj.lastUpdate);
      const progress = obj.progress;
      
      return (
        (progress < 70 && daysToDealline < 0) ||
        (progress < 50 && daysToDealline <= 7) ||
        (progress < 30 && daysToDealline <= 14)
      );
    });
    
    return overdueGoals;
  }
  
  /**
   * Create specific action for an overdue goal
   */
  async createActionForGoal(goal: StrategicObjective): Promise<OverdueGoalAction | null> {
    const assignedAgent = this.determineResponsibleAgent(goal);
    const actionType = this.determineActionType(goal);
    const recommendations = this.generateRecommendations(goal);
    const priority = this.calculatePriority(goal);
    
    if (!assignedAgent || !actionType) return null;
    
    return {
      goalId: goal.id,
      goalTitle: goal.title,
      assignedAgent,
      actionType,
      priority,
      recommendations,
      deadline: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000) // 7 days from now
    };
  }
  
  /**
   * Submit action through governance system for autonomous execution
   */
  async submitGoalAction(action: OverdueGoalAction): Promise<void> {
    const recommendation = {
      title: `Strategic Goal Recovery: ${action.goalTitle}`,
      action: action.actionType,
      owner: action.assignedAgent,
      risk: action.priority === 'high' ? 'medium' : 'low', // Medium risk for strategic items
      canary_n: 15, // Higher canary for strategic actions
      spend_cents: 0, // Keep zero-spend for autonomous execution
      payload: {
        goalId: action.goalId,
        recommendations: action.recommendations,
        deadline: action.deadline.toISOString(),
        autoGenerated: true
      },
      rationale: `Goal "${action.goalTitle}" is behind target. Autonomous execution initiated to recover progress through ${action.actionType}.`
    };
    
    console.log(`🎯 Strategic Executor: Auto-assigning ${action.assignedAgent} to recover goal "${action.goalTitle}"`);
    
    // Submit through governance system
    await actOnRecommendation(recommendation);
    
    // Update agent with new assignment
    await storage.updateAgent(action.assignedAgent, {
      lastReport: `AUTO-ASSIGNED: Strategic goal recovery for "${action.goalTitle}" - executing ${action.actionType}`,
      lastActive: new Date()
    });
  }
  
  /**
   * Determine which agent should be responsible for a goal
   */
  private determineResponsibleAgent(goal: StrategicObjective): string {
    const title = goal.title.toLowerCase();
    
    // Revenue-related goals
    if (title.includes('revenue') || title.includes('sales') || title.includes('conversion')) {
      return 'cro';
    }
    
    // Customer-related goals  
    if (title.includes('customer') || title.includes('retention') || title.includes('satisfaction')) {
      return 'cco';
    }
    
    // Marketing-related goals
    if (title.includes('marketing') || title.includes('brand') || title.includes('awareness') || title.includes('leads')) {
      return 'cmo';
    }
    
    // Operational goals
    if (title.includes('efficiency') || title.includes('cost') || title.includes('process') || title.includes('operations')) {
      return 'coo';
    }
    
    // Default to CRO for general business goals
    return 'cro';
  }
  
  /**
   * Determine appropriate action type for the goal
   */
  private determineActionType(goal: StrategicObjective): string {
    const title = goal.title.toLowerCase();
    const progress = goal.progress;
    
    if (progress < 30) {
      // Critical intervention needed
      if (title.includes('revenue')) return 'emergency_revenue_campaign';
      if (title.includes('customer')) return 'customer_recovery_program';
      if (title.includes('marketing')) return 'intensive_marketing_blitz';
      return 'strategic_intervention_plan';
    } else if (progress < 50) {
      // Moderate intervention
      if (title.includes('revenue')) return 'revenue_acceleration_tactics';
      if (title.includes('customer')) return 'customer_engagement_boost';
      if (title.includes('marketing')) return 'targeted_marketing_push';
      return 'performance_optimization';
    } else {
      // Light course correction
      if (title.includes('revenue')) return 'revenue_optimization';
      if (title.includes('customer')) return 'customer_experience_enhancement';
      if (title.includes('marketing')) return 'marketing_refinement';
      return 'goal_alignment_adjustment';
    }
  }
  
  /**
   * Generate specific recommendations for goal recovery
   */
  private generateRecommendations(goal: StrategicObjective): string[] {
    const title = goal.title.toLowerCase();
    const progress = goal.progress;
    const urgency = progress < 30 ? 'critical' : progress < 50 ? 'high' : 'moderate';
    
    const recommendations: string[] = [];
    
    if (title.includes('revenue')) {
      if (urgency === 'critical') {
        recommendations.push(
          'Launch emergency sales blitz with existing prospects',
          'Implement aggressive pricing incentives',
          'Activate all dormant sales channels',
          'Deploy CEO for key account rescue missions'
        );
      } else {
        recommendations.push(
          'Increase sales team activity by 30%',
          'Launch targeted upselling campaign',
          'Optimize conversion funnel bottlenecks'
        );
      }
    }
    
    if (title.includes('customer')) {
      if (urgency === 'critical') {
        recommendations.push(
          'Immediate customer outreach program',
          'Emergency customer success interventions',
          'Launch win-back campaigns for at-risk accounts',
          'Deploy retention specialists to key accounts'
        );
      } else {
        recommendations.push(
          'Increase customer engagement touchpoints',
          'Deploy satisfaction surveys and rapid response',
          'Enhance customer support response times'
        );
      }
    }
    
    if (title.includes('marketing')) {
      if (urgency === 'critical') {
        recommendations.push(
          'Launch emergency brand awareness campaign',
          'Activate all marketing channels simultaneously',
          'Deploy influencer partnerships immediately',
          'Increase ad spend by 50% on proven channels'
        );
      } else {
        recommendations.push(
          'Optimize underperforming marketing channels',
          'Launch A/B tests on key campaigns',
          'Increase content production velocity'
        );
      }
    }
    
    // Default recommendations
    if (recommendations.length === 0) {
      recommendations.push(
        'Conduct immediate progress audit',
        'Identify and remove execution blockers',
        'Reallocate resources to highest-impact activities',
        'Implement daily progress tracking'
      );
    }
    
    return recommendations;
  }
  
  /**
   * Calculate priority level for goal action
   */
  private calculatePriority(goal: StrategicObjective): 'low' | 'medium' | 'high' {
    const progress = goal.progress;
    const daysToDealline = this.getDaysToDeadline(goal.lastUpdate);
    
    // High priority: Very behind or very urgent
    if (progress < 30 || daysToDealline < 0) return 'high';
    
    // Medium priority: Somewhat behind and moderately urgent  
    if (progress < 50 && daysToDealline < 14) return 'medium';
    
    // Low priority: Course correction needed
    return 'low';
  }
  
  /**
   * Calculate days until deadline (negative means overdue)
   */
  private getDaysToDeadline(lastUpdate: Date): number {
    const now = new Date();
    const quarterEnd = this.getQuarterEnd();
    return Math.ceil((quarterEnd.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));
  }
  
  /**
   * Get end of current quarter as default deadline
   */
  private getQuarterEnd(): Date {
    const now = new Date();
    const quarter = Math.ceil((now.getMonth() + 1) / 3);
    const year = now.getFullYear();
    
    switch (quarter) {
      case 1: return new Date(year, 2, 31); // March 31
      case 2: return new Date(year, 5, 30); // June 30  
      case 3: return new Date(year, 8, 30); // September 30
      case 4: return new Date(year, 11, 31); // December 31
      default: return new Date(year, 11, 31);
    }
  }
}

export const strategyExecutor = new StrategyExecutor();